services:
  postgresdb:
    image: postgres:15.2-alpine
    restart: always
    ports:
      - 3000:5432
    environment:
      POSTGRES_PASSWORD: example
  fds:
    image: maven:3.9.1-eclipse-temurin-17
    working_dir: /fds
    volumes:
      - ./:/fds
    ports:
      - 8080:8080
    command: ["--spring.datasource.url=jdbc:postgresql://postgres:5432/example", "mvn spring-boot:run"]
    depends_on:
      - postgresdb
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb:5432/postgres
      SERVER_PORT: 8080
      ZOOKEEPER_CONNECTIONSTRING: zoo1:2181,zoo2:2181,zoo3:2181


  # DB administration
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080