services:
    postgresdb1:
        image: postgres:15.2-alpine
        restart: always
        ports: 
            - 3000:5432
        environment:
            POSTGRES_PASSWORD: example
    postgresdb2:
        image: postgres:15.2-alpine
        restart: always
        ports:
            - 3001:5432
        environment:
            POSTGRES_PASSWORD: example
    postgresdb3:
        image: postgres:15.2-alpine
        restart: always
        ports:
            - 3002:5432
        environment:
            POSTGRES_PASSWORD: example

    fds1:
        image: maven:3.9.1-eclipse-temurin-17
        working_dir: /fds
        volumes:
            - ./:/fds
        ports: 
            - 8082:8080
        command: mvn spring-boot:run
        depends_on:
            - postgresdb1
        environment:
#            - SPRING_DATASOURCE_URL = jdbc:postgresql://postgresdb1:5432/postgres
            - server.port=8083
            - zookeeper.connectionString=zoo1:2181,zoo2:2181,zoo3:2181
#            SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb1:5432/postgres
    fds2:
        image: maven:3.9.1-eclipse-temurin-17
        working_dir: /fds
        volumes:
            - ./:/fds
        ports:
            - 8083:8080
        command: mvn spring-boot:run
        depends_on:
            - postgresdb2
        environment:
#            SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb2:5432/postgres
            - server.port=8083
            - zookeeper.connectionString=zoo1:2181,zoo2:2181,zoo3:2181
    fds3:
        image: maven:3.9.1-eclipse-temurin-17
        working_dir: /fds
        volumes:
            - ./:/fds
        ports:
            - 8084:8080
        command: mvn spring-boot:run
        depends_on:
            - postgresdb3
        environment:
#            - SPRING_DATASOURCE_URL = jdbc:postgresql://postgresdb3:5432/postgres
#            SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb3:5432/postgres
            - server.port=8084
            - zookeeper.connectionString=zoo1:2181,zoo2:2181,zoo3:2181
# DB administration
#    adminer:
#        image: adminer
#        restart: always
#        ports:
#          - 8081:8080